SECRET = 'ihxq2MKyjX_XRxdxQIbXLYD1rJohSUpY9QGwbW-AZC1kV0VP-YiZVk4nxvyOEIfv'
AUTH0_DOMAIN = 'udacfsnd.us.auth0.com'
ALGORITHMS = ['RS256']
API_AUDIENCE = 'Casting'
CLIENT_ID = 'nBEglxlDSNtkW33pVuNyFYpXhPdz6PzG'
